dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 32
  dataset_path: ImageNet22k
  centering: sinkhorn_knopp
  pretrained_weights: "/home/ec2-user/dinov2/weights/dinov2_vitl14_pretrain.pth"  # Added by GV
student:
  arch: vit_large
  patch_size: 14
  drop_path_rate: 0.4
  # ffn_layer: swiglufused
  ffn_layer: "mlp"  # Changed by GV to match the weights
  block_chunks: 4
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 500
  weight_decay_end: 0.2
  base_lr: 2.0e-04  # learning rate for a batch size of 1024
  warmup_epochs: 80
  layerwise_decay: 1.0
crops:
  global_crops_size: 518  # Added by GV to match the pretrained weights
  local_crops_size: 98